name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/leo123-tto
          dst: gitee/leo312
          dst_key: ${{ secrets.GITEE_PRIVATE_TOKEN }}
          dst_account: leo312
          static_list: lawyer-fee-calculator
          force_update: true
          debug: true
